Minor update to jenkinsfile

diff --git a/llvm/Jenkinsfile b/llvm/Jenkinsfile
--- a/llvm/Jenkinsfile
+++ b/llvm/Jenkinsfile
@@ -52,16 +52,16 @@ git log -3
 
 def runTests(String targetSuffix) {
     stage("Run tests (${targetSuffix})") {
-        updateGithubStatus("Running check-all-${targetSuffix} tests...")
+        updateGithubStatus("Running check-${targetSuffix} tests...")
         sh """#!/usr/bin/env bash
 set -xe
 
 cd \${WORKSPACE}/llvm-build
 # run tests
 rm -fv "\${WORKSPACE}/llvm-test-output.xml"
-ninja check-all-${targetSuffix} \${JFLAG} || echo "Some ${targetSuffix} tests failed!"
+ninja check-${targetSuffix} \${JFLAG} || echo "Some check-${targetSuffix} tests failed!"
 mv -fv "\${WORKSPACE}/llvm-test-output.xml" "\${WORKSPACE}/llvm-test-output-${targetSuffix}.xml"
-echo "Done running ${targetSuffix} tests"
+echo "Done running check-${targetSuffix} tests"
 """
         junit healthScaleFactor: 2.0, testResults: "llvm-test-output-${targetSuffix}.xml"
     }
@@ -131,11 +131,14 @@ ninja ${JFLAG}
 
 # install
 ninja install
+
+# Remove all old JUnit XML files:
+rm -fv ${WORKSPACE}/llvm-test-*.xml
 '''
     }
-    runTests('cheri128')
+    runTests('all')
     // No need to rerun the full test suite, only run CHERI-specific  tests for 256
-    runTests('cheri256-only')
+    runTests('all-cheri256-only')
 
     stage("Archive artifacts") {
         updateGithubStatus("Archiving artifacts...")
@@ -206,7 +209,7 @@ node(nodeLabel) {
     try {
         env.label = nodeLabel
         env.SDKROOT_DIR = "${env.WORKSPACE}/sdk"
-        env.JFLAG = "-j20"
+        env.JFLAG = "-j 20"
         doBuild()
         // Scan for compiler warnings
         warnings canComputeNew: false, canResolveRelativePaths: true, consoleParsers: [[parserName: 'Clang (LLVM based)']]
